version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo Installing packages ...
      - npm install
  build:
    commands:
      - echo Building ...
      - npm run build

  post_build:
    commands:
      - echo Build completed 
artifacts:
  files:
    - message.js
